app:
  minDelaySeconds: 3
  maxDelaySeconds: 10
  topic:
    ping: topic.ping
    pong: topic.pong
kafka:
  bootstrapServers: localhost:9092
  kafkaAppId: ping-pong
  autoOffsetReset: latest
  groupId: test
  enableAutoCommit: true
  autoCommitInterval: 1000
  serializer: org.apache.kafka.common.serialization.StringSerializer
  deserializer: org.apache.kafka.common.serialization.StringDeserializer
logging.level.com.cedrus: DEBUG
